openapi: 3.0.0
info: 
  title: Contract for todo api
  version: 1.0.0
components:
  # securitySchemes:
  #   bearerAuth:
  #     type: http
  #     scheme: bearer
  #     bearerFormat: JWT
  schemas:
    $ref: "./schemas/index.yaml"
paths:
  /todos/{todoId}:
    $ref: "./paths/todo/todo-id.yaml"
  



