name: Package for todo api - demyst data

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 18.2.0
            registry-url: https://npm.pkg.github.com/
            scope: '@hk-boilerplate'
      - run: npm version 1.0.${{github.run_id}}${{github.run_attempt}} --no-git-tag-version
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}